### ISSUE TITLE
[IMP] [15.0] hr_contract: Cần fill dữ liệu contract type cho contract??

### ISSUE THREAD

**Issue by davidtranhp** [Viindoo/OpenUpgrade#277]
https://github.com/Viindoo/OpenUpgrade/blob/946bef1077de07e5841bdf4f6d82e22236a09851/openupgrade_scripts/scripts/hr_contract/15.0.1.0/upgrade_analysis_work.txt#L5-L6

**Comment by vietphuong97** [comment]
Vì trường `contract type` không `required` và việc thiết lập 1 bản ghi `contract type` là không xác định nên em không xử lý gì về chỗ này anh ạ. @davidtranhp 

Trong trường hợp muốn điền giá trị này vào hợp đồng thì sẽ phải cần xử lý 1 số việc như sau:
1. Tạo mẫu 1 `contract type`
2. Thiết lập trường quy tắc thuế `personal_tax_rule_id` trên `contract type` <Chưa xác định được là quy tắc theo quốc gia nào>
3. Thiết lập mẫu 1 quy tắc thuế `personal.tax.rule`

**Comment by royle-vietnam** [comment]
@davidtranhp `hr.contract.type` là model mới, và không có data sẵn, nên không phải làm gì anh ạ
CC @vietphuong10

**Comment by royle-vietnam** [comment]
hr.contract.type là model mới, và không có data sẵn, nên không phải làm gì ạ
