### ISSUE TITLE
[15.0 -> 16.0] Khai báo rename_module cho 2 module google_drive và google_spreadsheet

### ISSUE THREAD

**Issue by daiduongnguyen-odoo** [Viindoo/OpenUpgrade#349]
2 module này lên 16 odoo bỏ đi do một số vấn đề kỹ thuật, tuy nhiên nó đã được mang trở lại Viindoo dưới tên lần lượt là viin_google_drive và viin_google_spreadsheet, check ở task https://viindoo.com/web#id=49527&cids=1&menu_id=289&action=409&active_id=231&model=project.task&view_type=form

Khi làm PR cho OCA thì ta không khai báo, chỉ khải báo khi làm cho Viindoo thôi

**Comment by daiduongnguyen-odoo** [comment]
@royleviindoo  Cái này e nghĩ là khi chạy migrate thì nên điền  kiểu là
`google_drive: viin_google_drive`
`google_spreadsheet`: `viin_google_spreadsheet` chứ nếu điền luôn thì test sẽ chết anh ạ

**Comment by royle-vietnam** [comment]
> @royleviindoo Cái này e nghĩ là khi chạy migrate thì nên điền kiểu là `google_drive: viin_google_drive` `google_spreadsheet`: `viin_google_spreadsheet` chứ nếu điền luôn thì test sẽ chết anh ạ

ok em, cũng hợp lý, làm PR giúp anh nhé
