### ISSUE TITLE
[15.0 -> 16.0] Module ở 15 nhưng lên 16 xóa hoàn toàn và những asset của vẫn còn -> lỗi

### ISSUE THREAD

**Issue by daiduongnguyen-odoo** [Viindoo/OpenUpgrade#519]
![image](https://github.com/Viindoo/OpenUpgrade/assets/56789189/52b6b0cb-b7e1-407c-87bf-e298ed11d8f9)
ở repo `odoo-tvtma15`  có module `viin_website_product_add_to_cart_snippet`  lên 16 bị xóa nhưng mấy cái asset của nó vẫn còn nên khi truy cập vô website hay bất kỳ giao diện khác là lỗi như hình
Em đã thử
1. Xóa asset (viết vào con to_base)
2. Xóa xml_id trong `viin_website_product_add_to_cart_snippet` mà có cái đoạn nó load snipet
nhưng không được .

**Comment by daiduongnguyen-odoo** [comment]
cc anh @royleviindoo
Mọi người có cao kiến gì cho cái này không ạ
@nguyenvietlam0640 @SonCrits @duyquyen96 @vietphuong10 @ngochung207 @ngochuy97hp

**Comment by ngochuy97hp** [comment]
@duong77476 em xem cái asset đấy có noupdate không?

**Comment by daiduongnguyen-odoo** [comment]
> @duong77476 em xem cái asset đấy có noupdate không?

HÌnh như ko anh ạ, nhưng e xóa cả trực tiếp trên db rồi mà ko được nhỉ
![image](https://github.com/Viindoo/OpenUpgrade/assets/56789189/b9f5287e-caa0-45b9-94a9-c2b3042df084)

**Comment by ngochuy97hp** [comment]
@duong77476 con này đã merge vào website_sale, em lấy code mới nhất của openupgrade chưa, anh mig thử thì không bị

**Comment by daiduongnguyen-odoo** [comment]
> @duong77476 con này đã merge vào website_sale, em lấy code mới nhất của openupgrade chưa, anh mig thử thì không bị

Em chạy full module cơ, để thử chạy mỗi con này với website sale xem bị ko

**Comment by daiduongnguyen-odoo** [comment]
> @duong77476 con này đã merge vào website_sale, em lấy code mới nhất của openupgrade chưa, anh mig thử thì không bị

Em cài chỉ `website_sale` và `viin_website_product_add_to_cart_snippet` thì vẫn lỗi, sau khi xử lý bằng cách xóa ở cả `ir.asset` và xóa cái `web.assets_frontend_lazy.min.js` ở `ir.attachment` để nó tạo lại asset thì ok hết lỗi, em sẽ xử như vậy ở migration con `to_base`. 
BTW , a chạy mig kiểu gì mà không bị vậy , openupgrade của em hầu như mới nhất mà
cc @royleviindoo

**Comment by ngochuy97hp** [comment]
Anh chạy odoo, tvtmaddons, odoo-tvtma, openupgrade, odoo-openupgrade-tvtmaaddons, odoo-upgrade-tvtma không bị

**Comment by daiduongnguyen-odoo** [comment]
> Anh chạy odoo, tvtmaddons, odoo-tvtma, openupgrade, odoo-openupgrade-tvtmaaddons, odoo-upgrade-tvtma 

Hay e cắm thêm nhiều  `addons` quá nhỉ, đây là config chạy migrate của em
--addons-path=/git/odoo16/addons,/git/tvtmaaddons16,/git/erp16,/git/odoo-tvtma16,/git/backend_theme16,/git/branding16,/git/odoo-web_gantt16,/git/saas-infrastructure-common16,/git/saas-infrastructure16,/git/OpenUpgradeViindoo16
--load=base,web,to_base,openupgrade_framework
--limit-time-real=1000000
--http-port=8016
-d v15_mig_viindooooo4
-u all
--upgrade-path=/git/OpenUpgradeViindoo16/openupgrade_scripts/scripts,/git/odoo-openupgrade-tvtmaaddons16,/git/odoo-openupgrade-erponline-enterprise16,/git/odoo-upgrade-tvtma16,/git/odoo-openupgrade-branding16,/git/odoo-openupgrade-saas-infrastructure16
